### ISSUE TITLE
append data in the front

### ISSUE THREAD

**Issue by madneal** [Idnan/like-on-github#17]
I believe a better way to append data is in the front of the file, instead of the end of the file. So I make this [pr](https://github.com/Idnan/like-on-github/pull/16) for this feature.
Could you review it and consider about its value. It will wonderful that you can merge this. Any suggestions are welcome. Thanks.

**Comment by madneal** [comment]
@Idnan Could you spare some time to handle this? It will be better to handle it .

**Comment by Idnan** [comment]
@neal1991 thanks for the PR. I will check today.
