### ISSUE TITLE
Add option for reverse order adding

### ISSUE THREAD

**Issue by tunnckoCore** [Idnan/like-on-github#23]
Hi. 3rd day using it and noticed that it adds them in ASC order. Would be great to have most recent at the top - both for the day, and for each item.

so something like that

```
- October 23
  + latest link (17:38h)
  + previous (15:21h)
- October 22
  + last link of October 22
  + first link
- October 21
  + etc..
```

**Comment by tunnckoCore** [comment]
Hey @Idnan, any progress? I really used that extension aggressively everyday from october and collected huge collection of resources. And what to be in reverse order, because it's not comfortable someone to scroll to the bottom to see the most recent links.

I'll try to find some time to look at the code and suggest a PR.

**Comment by Idnan** [comment]
@olstenlarck thank you for reporting the issue. It was [fixed](https://github.com/Idnan/like-on-github/pull/16) some time ago but unfortunately I forgot to upload the updated version to chrome store. I have just done that, try updating after an hour or so

**Comment by tunnckoCore** [comment]
erm.. looking on the PR code.. it seems like total switch and not and added option? What that means? That, now when i have tons of links it will start prepending to whole that list?! Also i should reverse the list manually?

**Comment by Idnan** [comment]
For the existing content, it will not be touched. It will only update the links list for the current date
