### ISSUE TITLE
Backspace and such not work the inputs

### ISSUE THREAD

**Issue by tunnckoCore** [Idnan/like-on-github#24]
Heya there! Just happened to need to edit the title and commit message, so just found that Backspace and even the arrows not work. Even ctrl+backspace, ctrl+left arrow and such.

**Comment by Idnan** [comment]
@olstenlarck it seems to be working fine for me. Could you please tell me your `OS` and `chrome version`.

**Comment by tunnckoCore** [comment]
yea, that's old, it works
