### ISSUE TITLE
Feature request - editable title and a comment field

### ISSUE THREAD

**Issue by btbytes** [Idnan/like-on-github#8]
I'm using `like-on-git` ([see here](https://btbytes.github.io/liked/)), and I like it a lot. However, I often like to add comments to the links I saved. Currently, I have to pull down the git changes locally/edit the page on github to add comments. 

However, adding these two features to  `like-on-git` would make it extremely useful, IMHO.
1. showed a form to edit the title (sometimes the original titles are bad)
2. provide a textarea to enter a comment.

This is the mockup of the pop-up I have in mind: 

<img width="820" alt="like-on-git-feature-request" src="https://cloud.githubusercontent.com/assets/1047/18225218/a4eea890-71bb-11e6-8a0e-193c331adaf0.png">

**Comment by Idnan** [comment]
@btbytes thanks for the suggestion. Above said feature are implemented in [v2](https://github.com/Idnan/like-on-github/releases/tag/v2.0.0)

**Comment by btbytes** [comment]
Thank you !
